### ISSUE TITLE
Java Check Appears to Work Incorrectly in Safari in Some Situations

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/system-requirements-check#3]
Despite thinking it was working correctly when we were talking about the Safari version issue, it looks like the Java check does not work as it should in the following situation:

- **Safari Version 10.0.1** (current version)
- **Java Version 1.8.0_111** (current version)
- Java is Unchecked in the Security>Plugins window.

![screen shot 2016-11-14 at 3 05 16 pm](https://cloud.githubusercontent.com/assets/237349/20282794/db82b9a2-aa7b-11e6-865c-3ba61118f1f1.png)

What is also weird is when I toggle it on and off, there are times when it should be off in Safari, but it this test page reports it *is* on and it reports the current version. Just something to note for when you are testing. I also saw this for Flash, it was reporting it's on and up to date when I have it blocked for all but a few websites.

**Comment by Lin87** [comment]
Actually this is an expected behavior because of the way Apple implemented Java and Java plugin for Safari. Even Oracle has no solution for it unless there is an actual Java applet program trying to run. And if it failed, then it know the plugin is not installed or enabled. I will rephrase the message for the Java check and will not attempt to work a Java applet.

**Comment by Lin87** [comment]
Same for Flash. Turning on/off for each individual website is special to Safari only. The Java and Flash detection only know that you have them install, but it does not know that you have it turned on/off for a particular site.
