### ISSUE TITLE
Not showing version

### ISSUE THREAD

**Issue by TDDK** [oel-mediateam/system-requirements-check#4]
Hi,

The browser check doesn't show the Microsoft Edge version in the "tiny format" and when using Edge, it says I use Chrome (I do know that Edge is built on the Chromium engine but it's not "Google Chrome"). Is there any possibility, that you can fix this?
![browser versions](https://user-images.githubusercontent.com/22730893/210225486-323c550f-7953-4df6-8549-af8ba1626889.png)

Regards,
Theis

**Comment by Lin87** [comment]
Hello,

Thank you for reporting. The issues should be fixed in version 1.2.4. Plugin update is available for WordPress.

The version number is now displayed for Microsoft Edge.
![chrome](https://user-images.githubusercontent.com/2531526/210627058-ffcfd84d-b7d2-475d-84df-986f253ebbdf.png)

Microsoft Edge is now correctly identified as Microsoft Edge instead of Chrome. The icon is updated as well.
![edge](https://user-images.githubusercontent.com/2531526/210626874-6195e397-cf9c-4d3b-9172-06b43733adde.PNG)

Thanks!

**Comment by TDDK** [comment]
Thank you for the quick update, it's now showing the version.
